[package]
name = "korpsearch"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
miette.workspace = true
once_cell = "1.21.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["alloc", "derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
